spring.application.name=api-gateway
server.port=${PORT:8080}

# Disable Eureka
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# ================= USER SERVICE =================
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://user-service-5k5b.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# 🔥 REMOVE REWRITE (important)
# (kuch bhi filters mat daalo abhi)

# ================= RESUME SERVICE =================
spring.cloud.gateway.routes[1].id=resume-service
spring.cloud.gateway.routes[1].uri=https://resume-service-y9za.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/resume/**

# ================= RANKING SERVICE =================
spring.cloud.gateway.routes[2].id=ranking-service
spring.cloud.gateway.routes[2].uri=https://resume-ranking-system-ux0j.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/ranking/**

# ================= CORS =================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true