spring.application.name=api-gateway
server.port=${PORT:8080}

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=https://user-service-5k5b.onrender.com
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

# RESUME SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=resume-service
spring.cloud.gateway.server.webflux.routes[1].uri=https://resume-service-y9za.onrender.com
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/resume/**

# RANKING SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=ranking-service
spring.cloud.gateway.server.webflux.routes[2].uri=https://resume-ranking-system-ux0j.onrender.com
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ranking,/ranking/**
# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true