spring.application.name=ranking-service
server.port=${PORT:8080}
spring.application.name=ranking-service

# ❌ DATABASE DISABLED
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ❌ Eureka DISABLED
eureka.client.enabled=false