spring.application.name=user-service

server.port=${PORT:8080}

# ❌ DATABASE DISABLED (Render ke liye)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ❌ EUREKA DISABLED (abhi use nahi kar rahe)
eureka.client.enabled=false

# Optional logs
spring.jpa.show-sql=true