server.port=${PORT:8080}
spring.application.name=resume-service

# ❌ DATABASE DISABLED (for now)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ❌ Eureka DISABLED
eureka.client.enabled=false